substitutions:
  devicename: wifi_alarm

esphome:
  name: $devicename
  platform: ESP32
  board: lolin32
  includes:
    - tuya_mcu.h

# Enable logging
logger:
  level: VERBOSE

ota:
  password: !secret ota_password

web_server:
  port: 80

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO16

<<: !include common.yaml